SQOOP-3419: Refactor S3 tests for easier extensibility
apache/sqoop pull request #67
Opened 2019-01-14 10:47 UTC by szvasas

This patch covers the following changes:

- The original TestS3* tests are made abstract and generic, moved to the cloud package instead. The concrete cloud storage tests extend these abstract tests.
- S3TestUtils is broken into 3 classes: CloudCredentialsRule, CloudFileSystemRule and CloudTestDataSet
- S3CredentialGenerator and its only implementation DefaultS3CredentialGenerator have been simplified in the new CredentialGenerator class which is reusable for different cloud storage providers

2019-01-15 12:56 UTC, ebogi requested changes
Hi Szabolcs, thank you for this improvement, it is very elegant! I ran S3 tests with your patch successfully. I had only a minor finding otherwise your change LGTM.

2019-01-15 12:56 UTC, ebogi commented on src/test/org/apache/sqoop/cloud/CloudImportJobTestCase.java
> +  protected void failIfOutputFilePathContainingPatternExists(FileSystem s3Client, Path targetDirPath, String pattern) throws IOException {
Renaming of s3Client parameter has been missed. I would rename it to cloudFileSystem for example.

2019-01-15 12:56 UTC, ebogi commented on src/test/org/apache/sqoop/cloud/CloudImportJobTestCase.java
> +  protected void failIfOutputFilePathContainingPatternDoesNotExists(FileSystem s3Client, Path targetDirPath, String pattern) throws IOException {
Renaming of s3Client parameter has been missed. I would rename it to cloudFileSystem for example.

2019-01-15 14:04 UTC, ebogi approved these changes
Ship it!

2019-01-16 11:18 UTC, fszabo2 commented
Lgtm as well! Ship it!

2019-01-16 11:27 UTC, merged