SQOOP-3423 Let user pass password to connect Hive when it set to LDAP…
apache/sqoop pull request #70
Opened 2019-02-04 10:06 UTC by dionusos

… authentication

2019-02-06 09:07 UTC, szvasas requested changes
Hi @dionusos,

Thank you for the patch, it looks great, I have found only 2 minor things which need to be addressed before merging:
- hive.txt has also some documentation about the HiveServer2 connection("Currently only Kerberos authentication and text file format is supported with this option."), please make sure that it mentions the LDAP authentication too (

2019-02-06 09:07 UTC, szvasas commented on src/java/org/apache/sqoop/hive/HiveServer2ConnectionFactoryInitializer.java
> +  private String determineConnectionPassword(SqoopOptions sqoopOptions) {
Is the empty string ("") a legal password in LDAP environment?
If yes then we could eliminate this method and use sqoopOptions.getHs2Password() instead.

2019-05-03 11:12 UTC, dionusos commented on src/java/org/apache/sqoop/hive/HiveServer2ConnectionFactoryInitializer.java
> +  private String determineConnectionPassword(SqoopOptions sqoopOptions) {
As I found in LDAP environment empty password is possible so as the recommendation I removed the extra method.

2019-05-06 12:10 UTC, szvasas approved these changes

2019-05-06 13:38 UTC, ebogi commented
LGTM, ship it!

2019-05-06 13:48 UTC, merged