Bump Hadoop to 2.9.2
apache/sqoop pull request #73
Opened 2019-02-22 11:07 UTC by Fokko

We would like to bump Hadoop to make sure that it runs on GCP. Hadoop 2.6 isn't available anymore: https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.0

The latest stable release of Dataproc is on Hadoop 2.9.2: https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.3

This is similar to other cloud providers, and also applicable to vanilla Hadoop.

Jira: https://jira.apache.org/jira/browse/SQOOP-3429

2019-03-09 07:52 UTC, Fokko commented
Rebased to make the CI happy :)

2019-03-13 10:49 UTC, szvasas commented
Hi @Fokko, I agree with the patch if the tests run fine, there should be no problems upgrading from 2.8 to 2.9.2.
However since we still have the Ant build in the project can you please update the library version in ivy/libraries.properties:62 too?

2019-03-13 10:50 UTC, szvasas requested changes
Please update the library version in ivy/libraries.properties:62 too.

2019-03-13 14:29 UTC, Fokko commented
Thanks @szvasas for pointing out. I've updated the Ivy version as well.

2019-03-13 16:08 UTC, szvasas approved these changes

2019-03-13 16:11 UTC, merged